// Package resource implements blade's resource_library codegen: embedding files
// as C byte arrays plus an index, matching blade's builtin `resource` /
// `resource_index` output byte-for-byte (see blade-build
// src/blade/builtin_tools.py) so the generated symbols match what C++ consumers
// expect. blade-go invokes these via hidden `__gen-resource*` subcommands, the
// same architecture as blade's builtin_command.
package resource

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// varTable maps blade's regular_variable_name punctuation (,-/:\.+*) to '_'.
var varReplacer = strings.NewReplacer(
	",", "_", "-", "_", "/", "_", ":", "_", "\\", "_", ".", "_", "+", "_", "*", "_",
)

// RegularVarName converts a path to a valid C identifier fragment (blade's
// regular_variable_name).
func RegularVarName(name string) string { return varReplacer.Replace(name) }

func toUnix(p string) string { return strings.ReplaceAll(p, "\\", "/") }

// GenerateResource writes a C source embedding input's bytes as
// `const char RESOURCE_<var>[]` + `const unsigned int RESOURCE_<var>_len`.
// var is RegularVarName(input) -- input is the source path as blade names it.
func GenerateResource(input, output string) error {
	data, err := os.ReadFile(input)
	if err != nil {
		return err
	}
	varName := RegularVarName(input)
	var b bytes.Buffer
	fmt.Fprintf(&b, "const char RESOURCE_%s[] = {\n", varName)
	for i := 0; i < len(data); i += 12 {
		end := i + 12
		if end > len(data) {
			end = len(data)
		}
		hexes := make([]string, 0, end-i)
		for _, by := range data[i:end] {
			hexes = append(hexes, fmt.Sprintf("0x%02x", by))
		}
		comma := ""
		if i+12 < len(data) {
			comma = ","
		}
		fmt.Fprintf(&b, "  %s%s\n", strings.Join(hexes, ", "), comma)
	}
	b.WriteString("};\n")
	fmt.Fprintf(&b, "const unsigned int RESOURCE_%s_len = %d;\n\n", varName, len(data))
	return os.WriteFile(output, b.Bytes(), 0o644)
}

// GenerateIndex writes the resource index header + source. name is the library
// name, pkgPath its package; header/source are the output paths; sources are the
// resource source paths (as blade names them, i.e. pkg-joined). Matches blade's
// _generate_resource_index.
func GenerateIndex(name, pkgPath, header, source string, sources []string) error {
	fullName := RegularVarName(filepath.ToSlash(filepath.Join(pkgPath, name)))
	guard := "BLADE_RESOURCE_" + strings.ToUpper(fullName) + "_H_"
	indexName := "RESOURCE_INDEX_" + fullName
	headerFwd := toUnix(header)

	var h, c bytes.Buffer

	h.WriteString("// This file was automatically generated by blade\n")
	fmt.Fprintf(&h, "#ifndef %s\n#define %s\n\n", guard, guard)
	h.WriteString("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
	h.WriteString("#ifndef BLADE_RESOURCE_TYPE_DEFINED\n#define BLADE_RESOURCE_TYPE_DEFINED\n")
	h.WriteString("struct BladeResourceEntry {\n    const char* name;\n    const char* data;\n    unsigned int size;\n};\n#endif\n")

	c.WriteString("// This file was automatically generated by blade\n")
	fmt.Fprintf(&c, "#include \"%s\"\n\n", headerFwd)
	c.WriteString("#ifdef __has_attribute\n")
	c.WriteString("#  if __has_attribute(retain)\n#    define BLADE_RESOURCE_KEEP __attribute__((retain, used))\n")
	c.WriteString("#  elif __has_attribute(used)\n#    define BLADE_RESOURCE_KEEP __attribute__((used))\n")
	c.WriteString("#  else\n#    define BLADE_RESOURCE_KEEP\n#  endif\n")
	c.WriteString("#else\n#  define BLADE_RESOURCE_KEEP\n#endif\n\n")
	c.WriteString("BLADE_RESOURCE_KEEP\n")
	fmt.Fprintf(&c, "const struct BladeResourceEntry %s[] = {\n", indexName)

	for _, s := range sources {
		entryVar := RegularVarName(s)
		rel, err := filepath.Rel(pkgPath, s)
		if err != nil {
			rel = s
		}
		entryName := toUnix(rel)
		info, err := os.Stat(s)
		if err != nil {
			return err
		}
		size := info.Size()
		fmt.Fprintf(&h, "// %s\n", entryName)
		fmt.Fprintf(&h, "extern const char RESOURCE_%s[%d];\n", entryVar, size)
		fmt.Fprintf(&h, "extern const unsigned RESOURCE_%s_len;\n", entryVar)
		fmt.Fprintf(&c, "    { \"%s\", RESOURCE_%s, %d },\n", entryName, entryVar, size)
	}

	c.WriteString("};\n")
	c.WriteString("BLADE_RESOURCE_KEEP\n")
	fmt.Fprintf(&c, "const unsigned %s_len = %d;\n", indexName, len(sources))

	fmt.Fprintf(&h, "// Resource index\nextern const struct BladeResourceEntry %s[];\nextern const unsigned %s_len;\n\n", indexName, indexName)
	h.WriteString("#ifdef _MSC_VER\n")
	fmt.Fprintf(&h, "#  ifdef _M_IX86\n#    pragma comment(linker, \"/INCLUDE:_%s\")\n#    pragma comment(linker, \"/INCLUDE:_%s_len\")\n", indexName, indexName)
	fmt.Fprintf(&h, "#  else\n#    pragma comment(linker, \"/INCLUDE:%s\")\n#    pragma comment(linker, \"/INCLUDE:%s_len\")\n#  endif\n", indexName, indexName)
	h.WriteString("#endif\n\n")
	h.WriteString("#ifdef __cplusplus\n}  // extern \"C\"\n#endif\n\n")
	fmt.Fprintf(&h, "#endif  // %s\n", guard)

	if err := os.WriteFile(header, h.Bytes(), 0o644); err != nil {
		return err
	}
	return os.WriteFile(source, c.Bytes(), 0o644)
}
